---
- hosts: all

  vars:
    application_dir: '/Applications'
    applications:
      - alfred
      - bartender
      - caffeine
      - chronomate
      - clamxav
      - cyberduck
      - dropbox
      - firefox
      - flux
      - google-chrome
      - gpgtools
      - instacast1
      - iterm2
      - moom
      - opera
      - phpstorm
      - sequel-pro
      - skitch1
      - skype
      - spotify
      - sublime-text3
      - the-unarchiver
      - tunnelblick
      - vagrant
      - virtualbox
      - vlc
    brews:
      - rsync
      - ssh-copy-id
      - wget
      - zsh
    caskroom_dir: '/usr/local/caskroom'
    zsh_path: '/usr/local/bin/zsh'
    home_dir: '/Users/opdavies'

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    - include: tasks/zsh.yml tags=zsh